### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Booligoosh** [daneden/Zeitgeist#20]
Hi, thanks for making this app! It's really nice 😍

Ran into a slight issue, my computer was getting a little slow and I was wondering what was causing it. I had a look in Activity Monitor and it was using up 2.76GB of RAM. After quitting it and reopening, the RAM usage went back down to 33MB.

I'm happy to provide any debug details, although I'm not sure if any useful ones can be retrieved now that I've closed and reopened it.

My computer has been powered on for 4 days so Zeitgeist can't have been open for any longer than that.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/14034891/92369045-d9f07380-f13b-11ea-8289-0912065984e7.png">

**Comment by daneden** [comment]
Hey @Booligoosh! I’ve also noticed this on macOS and will make some effort to debug it for v2.0.2.

**Comment by daneden** [comment]
Belated update here, after weeding out a handful of reference cycles in the app, I *think* the majority of memory leak causes should be gone from the app now.

I haven't released the v3 build via GitHub since I'm hoping to switch to App Store distribution (which will make updating easier), so I'll keep this issue open and close it once v3 (which provides these fixes) is available!

**Comment by Booligoosh** [comment]
Awesome, thanks!! 🙏
