### ISSUE TITLE
Blurried name

### ISSUE THREAD

**Issue by 0w9** [daneden/Zeitgeist#70]
Hello! I would have two questions and a error. 

* How do I join beta?
* What is the app subscription I heard from?

Also, my name is blurried in the app. Is there any way to remove this? 
![42D16264-5386-42FA-836C-1826BFB68681](https://user-images.githubusercontent.com/79471472/180887235-8aa36887-6721-4fb4-8c16-0320e6fbd123.png)

**Comment by daneden** [comment]
Hey @0w9!

The v3 beta is not yet open to the public, but I will add a link to join the TestFlight in the PR when I’m ready for external testers: #67 

> What is the app subscription I heard from?
The in-app subscription used to provide access to push notifications, but I recently made this feature available to all Zeitgeist users. If you still see references to in-app subscriptions, would you mind sharing a screenshot so I can remove it?

> My name is blurried in the app. Is there any way to remove this?
This happens when Zeitgeist is unable to decode your account information from the Vercel API. This could be because the account name isn't set, which is a bug I recently discovered. You may be able to fix this by going to vercel.com/account and entering a name in the “Your Name” section. If the issue persists, please let me know and I’ll give you further instructions for debugging!
