### ISSUE TITLE
Enhanced logging

### ISSUE THREAD

**Issue by Gitnapp** [daneden/Zeitgeist#92]
> Please give a detailed description of the issue you’re experiencing or the feedback you’d like to provide.
> Feel free to attach any relevant screenshots or logs, and please keep the app version and device info in the issue!

App Version: 3.1		Device: iPhone 12
		OS: iOS 17.0.3

**Comment by daneden** [comment]
Thanks @Gitnapp for the suggestion! 

Zeitgeist’s current logs view only shows build logs, since these are now the only logs returned directly by Vercel’s API. However, a while ago, Vercel introduced [log drains](https://vercel.com/blog/log-drains), a feature allowing Vercel users and integration developers (like me) to have their build, function invocation, and request logs sent to a remote server.

I’m starting to investigate how I could natively integrate log drains into the Zeitgeist app. I’ll use this issue to track my progress.

**Comment by mfts** [comment]
Hi Dan, while that's a great idea. Vercel recently [started charging for log drains](https://vercel.com/changelog/log-drains-are-now-generally-available) and made it only available for Pro and higher plans.

**Comment by daneden** [comment]
@mfts ack, you're right. Even without that thorn, I was coming to the conclusion that there wasn't a good way to do this without requiring some additional user auth to keep them secure anyway. Unfortunately this feature will have to sit idle.
